name: Check and test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    env:
      SPRING_PROFILES_ACTIVE: stage
      JWT_SECRET_TEST: ${{ secrets.JWT_SECRET_TEST }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run checks
        run: gradle check --stacktrace --info
