name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  smoke-test:
    uses: ./.github/workflows/smoke-test.yml
    secrets: inherit
  
  deploy-to-docker:
    uses: ./.github/workflows/deploy-to-docker.yml
    secrets: inherit

  deploy-to-ec2:
    needs: deploy-to-docker
    uses: ./.github/workflows/deploy-to-ec2.yml
    secrets: inherit
