name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  junit-test:
    uses: ./.github/workflows/junit-gradle-tester.yml
    secrets: inherit

  deploy-to-docker:
    needs: junit-test
    uses: ./.github/workflows/deploy-to-docker.yml
    secrets: inherit

  deploy-to-ec2:
    needs: deploy-to-docker
    uses: ./.github/workflows/deploy-to-ec2.yml
    secrets: inherit

  smoke-test:
    needs: deploy-to-ec2
    uses: ./.github/workflows/smoke-test.yml
    secrets: inherit
