name: Deploy to EC2

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IPADRESS }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Logging in to Docker Hub..."
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            echo "Pulling latest Docker image..."
            docker pull diggykaze/intro-java:latest

            echo "Stopping old container..."
            docker stop intro-java-app || true
            docker rm intro-java-app || true

            echo "Starting new container with prod profile..."
            docker run -d \
              -p 80:8080 \
              --name intro-java-app \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e SPRING_DATASOURCE_URL="${{ secrets.DB_URL }}" \
              -e SPRING_DATASOURCE_USERNAME="${{ secrets.DB_USERNAME }}" \
              -e SPRING_DATASOURCE_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              diggykaze/intro-java:latest

            echo "Deployment finished."
