name: Deploy to EC2

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IPADRESS }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            # 1. Logga in på Docker Hub inifrån din EC2
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            
            # 2. Hämta den senaste bilden
            docker pull diggykaze/intro-java:latest
            
            # 3. Stoppa och ta bort den gamla containern om den körs
            docker stop intro-java-app || true
            docker rm intro-java-app || true
            
            # 4. Starta appen på nytt (mappad till port 80 utåt)
            docker run -d -p 80:8080 --name intro-java-app diggykaze/intro-java:latest
