name: Smoke Test

on:
  workflow_call:

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Test deployed app health endpoint
        run: |
          curl -f http://${{ secrets.EC2_IPADRESS }}/actuator/health

      - name: Test products endpoint
        run: |
          curl -f http://${{ secrets.EC2_IPADRESS }}/products
