name: Smoke Test

on:
  workflow_call:

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Debug target
        run: |
          echo "Testing: http://${{ secrets.EC2_IPADRESS }}"

      - name: Test homepage
        run: |
          curl -v -f --connect-timeout 10 --max-time 20 http://${{ secrets.EC2_IPADRESS }}/

      - name: Test health endpoint
        run: |
          curl -v -f --connect-timeout 10 --max-time 20 http://${{ secrets.EC2_IPADRESS }}/actuator/health
